version: '3'
services:
  # Service pour la base de données MySQL
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php73
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8000:80

  db:
    container_name: mysql8
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: prix_nobel
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
   

